#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Maze constants containing maze represented with costs to simulate walls and floors

Version:  69.420
Author:   MormonJesus69420
Date:     Yes, please
"""

import numpy as np

# Size of the maze
size = 101
# Cost of going through wall, very big to avoid path going through walls
w = 1000
# Cost used to draw path in matrix
path = w / 2
# Cost of going through floor, very low to encourage algorithm to use it
f = 1
# Cost array for movement in maze.py
cost_array = np.array(
        [[w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w,
          w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, w,
          w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w,
          w, w, w, w, w],
         [w, f, f, f, f, f, f, f, w, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, w, f,
          f, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f,
          w, f, f, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, f, f,
          f, f, f, f, w],
         [w, f, w, w, w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, f,
          w, w, w, w, w, f, w, w, w, w, w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, f,
          w, f, w, w, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, w,
          w, w, w, f, w],
         [w, f, f, f, w, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, w, f,
          f, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f,
          f, f, w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f,
          f, f, w, f, w],
         [w, w, w, f, w, f, w, w, w, f, w, f, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, w, w, f, w, f,
          w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, w,
          w, w, w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, f, w, f, w, f, w, w,
          w, f, w, f, w],
         [w, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f,
          w, f, f, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, w, f, w, f, f, f, f, f, w, f,
          f, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f,
          f, f, w, f, w],
         [w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, f,
          w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, w,
          w, w, w, f, w, f, w, f, w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, f, w, f,
          w, w, w, f, w],
         [w, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, f, f, w, f, w, f, w, f, w, f, f, f,
          f, f, w, f, f, f, f, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f,
          f, f, w, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, w, f, f, f, f, f, w, f,
          w, f, f, f, w],
         [w, f, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, w,
          w, w, w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, f, w, w, w, f, w, w, w, f, w, w, w, w, w, w,
          w, f, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, f,
          w, f, w, f, w],
         [w, f, f, f, w, f, f, f, f, f, f, f, w, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f,
          f, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f,
          f, f, w, f, f, f, f, f, f, f, w, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f,
          w, f, w, f, w],
         [w, w, w, f, w, f, w, w, w, f, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, f, w, w,
          w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, f,
          w, w, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, f,
          w, f, w, w, w],
         [w, f, f, f, w, f, w, f, w, f, w, f, w, f, f, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f,
          f, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f,
          w, f, f, f, w, f, f, f, f, f, f, f, w, f, w, f, f, f, w, f, f, f, f, f, f, f, f, f, f, f, w, f,
          w, f, f, f, w],
         [w, f, w, w, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, f, w, w, w, w, w, w,
          w, f, w, w, w, f, w, w, w, f, w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, f, w, f, w, f,
          w, f, w, f, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, f,
          w, w, w, f, w],
         [w, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f,
          f, f, f, f, w, f, w, f, w, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f, w, f,
          w, f, w, f, f, f, f, f, w, f, w, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f,
          w, f, f, f, w],
         [w, f, w, f, w, w, w, w, w, f, w, f, w, w, w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, w,
          w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, f,
          w, f, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, f, w, w,
          w, f, w, f, w],
         [w, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f,
          f, f, w, f, w, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f,
          w, f, f, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f, f, f, w, f, w, f, w, f, w, f, f, f, w, f,
          f, f, w, f, w],
         [w, f, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, f,
          w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, w, w, w, w, f,
          w, f, w, w, w, w, w, f, w, w, w, f, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, w, w, f, w, f,
          w, w, w, f, w],
         [w, f, w, f, w, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f, f, f, f, f, w, f, w, f, w, f, f, f,
          w, f, w, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f,
          f, f, w, f, f, f, w, f, w, f, f, f, w, f, w, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, w, f,
          w, f, f, f, w],
         [w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, w,
          w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, w, w, w, w, f, w, f, w, f, w, f, w, f, w, w,
          w, w, w, f, w, f, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, f,
          w, f, w, w, w],
         [w, f, w, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, w, f, w, f, f, f,
          w, f, w, f, f, f, w, f, w, f, f, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f,
          f, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f,
          w, f, w, f, w],
         [w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, f, w, w,
          w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, w,
          w, w, w, w, w, w, w, w, w, f, w, f, w, w, w, f, w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, w,
          w, f, w, f, w],
         [w, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f, w, f, w, f,
          f, f, w, f, f, f, f, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f,
          f, f, f, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f,
          w, f, f, f, w],
         [w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, f, w, f,
          w, w, w, f, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, w, w, f, w, f, w, f, w, f, w, w,
          w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, w, w, f,
          w, w, w, f, w],
         [w, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f,
          f, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f,
          f, f, f, f, w, f, w, f, w, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f,
          w, f, w, f, w],
         [w, f, w, w, w, f, w, f, w, f, w, f, w, w, w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, w,
          w, f, w, w, w, w, w, f, w, w, w, w, w, f, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, w,
          w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, w,
          w, f, w, f, w],
         [w, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, w, f, w, f, f, f, f, f, w, f, w, f, f, f,
          w, f, f, f, w, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, w, f, w, f, w, f, f, f, w, f, f, f,
          f, f, w, f, f, f, w, f, w, f, w, f, w, f, f, f, w, f, w, f, f, f, f, f, f, f, w, f, w, f, w, f,
          w, f, f, f, w],
         [w, w, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, f,
          w, w, w, f, w, f, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, w,
          w, w, w, f, w, w, w, f, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, f, w, f, w, f,
          w, f, w, w, w],
         [w, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f,
          f, f, w, f, w, f, f, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f, w, f, w, f,
          f, f, w, f, w, f, f, f, w, f, w, f, w, f, f, f, w, f, w, f, w, f, w, f, f, f, f, f, w, f, w, f,
          f, f, f, f, w],
         [w, f, w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, w, w, f, w, f,
          w, w, w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, f, w, f, w, w, w, f, w, f, w, f, w, f,
          w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, w,
          w, w, w, f, w],
         [w, f, f, f, w, f, f, f, f, f, f, f, w, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f,
          w, f, f, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f,
          w, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, f, f,
          f, f, w, f, w],
         [w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, f,
          w, f, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, f,
          w, f, w, w, w, f, w, w, w, f, w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, f, w, f, w, w, w, w,
          w, f, w, f, w],
         [w, f, w, f, w, f, f, f, f, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f,
          w, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, f, f,
          w, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f,
          w, f, w, f, w],
         [w, f, w, w, w, f, w, f, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, w,
          w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, f, w, f, w, f, w, w, w, w,
          w, w, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, f, w, f, w, f,
          w, f, w, w, w],
         [w, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, f, f, w, f, f, f, f, f, f, f, w, f, w, f,
          f, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, w, f, w, f, w, f, f, f,
          f, f, w, f, w, f, w, f, f, f, w, f, w, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f,
          w, f, f, f, w],
         [w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, f, w, f, w, f,
          w, w, w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, f, w, f, w, f, w, f, w, f, w, w,
          w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, w, w, f, w, w, w, w, w, w, w, f, w, w, w, f,
          w, w, w, f, w],
         [w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f,
          f, f, w, f, w, f, w, f, f, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f,
          f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, w, f, w, f,
          f, f, w, f, w],
         [w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, w,
          w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, f,
          w, w, w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, w,
          w, f, w, f, w],
         [w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f,
          f, f, w, f, f, f, w, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f,
          w, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f,
          f, f, w, f, w],
         [w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, f, w, f,
          w, w, w, f, w, w, w, f, w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, w, w, f, w, f, w, f, w, w,
          w, f, w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, w, w, w, w, w,
          w, w, w, f, w],
         [w, f, w, f, f, f, w, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f,
          w, f, f, f, f, f, f, f, w, f, f, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, w, f,
          f, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f, f, f,
          w, f, f, f, w],
         [w, f, w, w, w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, f,
          w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, f,
          w, w, w, f, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, w, w, f, w, f, w, w, w, w, w, f,
          w, f, w, f, w],
         [w, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f,
          w, f, w, f, w, f, f, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f, f, f, w, f, f, f,
          f, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f,
          f, f, w, f, w],
         [w, w, w, f, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, w, w, f, w, w, w, w, w, f,
          w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, f, w, w, w, w,
          w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, f, w, w,
          w, w, w, f, w],
         [w, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, f, f, f, f,
          w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, f, f, w, f, w, f, f, f,
          w, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f, f, f,
          f, f, w, f, w],
         [w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, f, w, f, w, w,
          w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, f, w, f, w, f, w, f, w, f,
          w, f, w, w, w, f, w, w, w, f, w, w, w, f, w, w, w, f, w, f, w, w, w, f, w, w, w, f, w, f, w, w,
          w, w, w, f, w],
         [w, f, w, f, f, f, w, f, w, f, w, f, w, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, w, f,
          f, f, f, f, f, f, w, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f,
          w, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f, w, f, w, f, f, f,
          f, f, w, f, w],
         [w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, w, w, w, w, f,
          w, w, w, w, w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, f, w, w, w, w, w, f,
          w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, w, w, w,
          w, f, w, f, w],
         [w, f, w, f, w, f, w, f, f, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f,
          w, f, w, f, f, f, w, f, f, f, f, f, f, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f,
          w, f, f, f, f, f, w, f, f, f, f, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f, w, f, f, f, f, f,
          w, f, f, f, w],
         [w, f, w, f, w, f, w, w, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w,
          w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, f,
          w, w, w, w, w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, f,
          w, w, w, w, w],
         [w, f, f, f, w, f, f, f, w, f, w, f, w, f, f, f, f, f, f, f, f, f, f, f, w, f, f, f, f, f, f, f,
          w, f, w, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f,
          f, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f,
          f, f, f, f, w],
         [w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, f,
          w, f, w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, f,
          w, f, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, w, w, f, w, f, w, f, w, w, w, f, w, w, w, w,
          w, w, w, f, w],
         [w, f, f, f, f, f, f, f, w, f, w, f, f, f, w, f, w, f, w, f, f, f, w, f, w, f, f, f, f, f, w, f,
          f, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f, f, f, w, f, w, f, w, f, f, f, f, f, w, f,
          w, f, f, f, w, f, w, f, f, f, f, f, w, f, w, f, w, f, w, f, f, f, w, f, w, f, f, f, f, f, f, f,
          f, f, w, f, w],
         [w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, w, w, f, w, f, w, f, w, w, w, f, w, w, w, f, w, w,
          w, w, w, w, w, w, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, w, w, f,
          w, w, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, w, w, w, w, f, w, f, w, w, w, f, w, f,
          w, w, w, w, w],
         [w, f, w, f, w, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f, f, f, w, f, w, f, f, f,
          f, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f,
          w, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f,
          w, f, f, f, w],
         [w, f, w, f, w, f, w, f, w, w, w, f, w, f, w, f, w, w, w, f, w, w, w, w, w, w, w, f, w, w, w, w,
          w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, w,
          w, w, w, f, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, w, w, f, w, f, w, f, w, w, w, w,
          w, f, w, f, w],
         [w, f, w, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f,
          f, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f,
          f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, w, f, w, f, f, f,
          f, f, w, f, w],
         [w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, w, w, f, w, w, w, w, w, f,
          w, f, w, f, w, w, w, f, w, f, w, w, w, w, w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, f,
          w, f, w, w, w, f, w, w, w, w, w, w, w, w, w, f, w, w, w, f, w, f, w, w, w, f, w, f, w, f, w, w,
          w, w, w, f, w],
         [w, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f,
          w, f, f, f, f, f, w, f, w, f, f, f, f, f, f, f, w, f, w, f, w, f, w, f, f, f, w, f, w, f, f, f,
          w, f, w, f, w, f, w, f, w, f, f, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f,
          f, f, f, f, w],
         [w, f, w, f, w, w, w, f, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, w,
          w, w, w, w, w, f, w, f, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, w,
          w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, f, w, f, w, w, w, f, w, f, w, w, w, w, w, f,
          w, w, w, f, w],
         [w, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f, f, f, w, f, f, f,
          f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, w, f, f, f, w, f, w, f,
          w, f, w, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f,
          w, f, f, f, w],
         [w, f, w, f, w, f, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, f, w, w, w, w,
          w, f, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, f, w, f, w, f,
          w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, f, w, f, w, f,
          w, f, w, w, w],
         [w, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f,
          f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f,
          w, f, f, f, f, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, f, f,
          w, f, f, f, w],
         [w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, w, w, f,
          w, w, w, f, w, w, w, w, w, f, w, w, w, f, w, f, w, w, w, f, w, w, w, f, w, f, w, f, w, w, w, f,
          w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, w,
          w, w, w, w, w],
         [w, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f,
          w, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f, w, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f,
          f, f, w, f, f, f, w, f, f, f, w, f, w, f, w, f, w, f, f, f, f, f, f, f, w, f, w, f, f, f, f, f,
          f, f, f, f, w],
         [w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, w, w, w, w, f, w, f, w, f, w, f, w, f, w, w,
          w, f, w, w, w, w, w, w, w, w, w, f, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, w,
          w, f, w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w,
          w, w, w, f, w],
         [w, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f,
          f, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f,
          w, f, w, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f,
          f, f, w, f, w],
         [w, w, w, w, w, f, w, f, w, f, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, w,
          w, w, w, f, w, f, w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, f, w, f,
          w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, f, w, w, w, f,
          w, w, w, f, w],
         [w, f, f, f, w, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, w, f, f, f,
          f, f, f, f, w, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f,
          f, f, w, f, w, f, w, f, f, f, f, f, f, f, f, f, w, f, f, f, f, f, f, f, f, f, w, f, w, f, f, f,
          w, f, f, f, w],
         [w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, f, w, f,
          w, w, w, w, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, w, w, w, w, w, w, f, w, w, w, w,
          w, w, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, f, w, f, w, w,
          w, f, w, f, w],
         [w, f, w, f, f, f, w, f, w, f, w, f, f, f, f, f, w, f, w, f, w, f, w, f, w, f, f, f, w, f, w, f,
          w, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f,
          f, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f, w, f, w, f, f, f, w, f, w, f,
          f, f, w, f, w],
         [w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, f, w, w, w, f, w, f,
          w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, f, w, w, w, f, w, w,
          w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, f,
          w, w, w, f, w],
         [w, f, w, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f,
          w, f, w, f, w, f, w, f, w, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f,
          w, f, f, f, f, f, w, f, w, f, w, f, w, f, f, f, w, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f,
          w, f, f, f, w],
         [w, f, w, w, w, f, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, f,
          w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, f, w, f, w, w, w, f, w, w, w, f,
          w, w, w, w, w, f, w, w, w, f, w, f, w, f, w, w, w, f, w, f, w, w, w, f, w, f, w, w, w, f, w, f,
          w, w, w, w, w],
         [w, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f,
          w, f, w, f, f, f, w, f, w, f, w, f, w, f, f, f, f, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f,
          f, f, f, f, w, f, f, f, f, f, w, f, w, f, w, f, w, f, w, f, f, f, w, f, w, f, w, f, f, f, w, f,
          f, f, f, f, w],
         [w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, f, w, w, w, f, w, f,
          w, f, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, f, w, f, w, w, w, f, w, f, w, f, w, f,
          w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, f, w, f, w, f, w, w,
          w, w, w, f, w],
         [w, f, f, f, f, f, f, f, w, f, w, f, w, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f, w, f, w, f,
          w, f, f, f, w, f, f, f, f, f, w, f, w, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f,
          f, f, w, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f, w, f, w, f, w, f,
          f, f, f, f, w],
         [w, w, w, w, w, w, w, f, w, w, w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, f, w, f, w, f,
          w, w, w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, w,
          w, f, w, w, w, f, w, w, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, f, w, f, w, f, w, f, w, f,
          w, w, w, w, w],
         [w, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, w, f,
          f, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f,
          w, f, f, f, w, f, w, f, f, f, w, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f, w, f, w, f, w, f,
          f, f, f, f, w],
         [w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, f, w, w,
          w, f, w, f, w, w, w, f, w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, w, w, f,
          w, w, w, f, w, w, w, f, w, w, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, w,
          w, w, w, f, w],
         [w, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, f, f, w, f, f, f,
          w, f, w, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f, w, f, w, f, w, f, f, f, f, f, f, f, w, f,
          f, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, w, f, w, f, f, f, f, f, w, f, w, f, f, f, f, f,
          f, f, w, f, w],
         [w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, f,
          w, w, w, w, w, f, w, w, w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, w,
          w, f, w, w, w, w, w, w, w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, f, w, f, w, w, w, f, w, w,
          w, f, w, f, w],
         [w, f, w, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f,
          w, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f,
          f, f, w, f, f, f, f, f, f, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f,
          f, f, w, f, w],
         [w, f, w, w, w, w, w, f, w, w, w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, f,
          w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, w, w, w,
          w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, w, w, f, w, f, w, f, w, w, w, f, w, f, w, w, w, f,
          w, w, w, f, w],
         [w, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, w, f, w, f, w, f, f, f, f, f, f, f, w, f,
          w, f, f, f, w, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f,
          f, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, f, f, w, f, w, f,
          w, f, w, f, w],
         [w, f, w, w, w, f, w, w, w, f, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, f, w, f, w, w, w, f,
          w, w, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, f, w, w, w, w, w, f, w, f, w, f,
          w, w, w, w, w, f, w, w, w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, f, w, f,
          w, f, w, f, w],
         [w, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f,
          w, f, w, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f, f, f,
          f, f, w, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f,
          w, f, w, f, w],
         [w, f, w, f, w, w, w, f, w, w, w, f, w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, w,
          w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, w,
          w, f, w, f, w, w, w, f, w, f, w, f, w, w, w, f, w, w, w, f, w, f, w, w, w, f, w, w, w, f, w, f,
          w, f, w, f, w],
         [w, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, f, f, w, f,
          f, f, w, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f,
          f, f, w, f, w, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f,
          w, f, w, f, w],
         [w, w, w, w, w, f, w, w, w, f, w, f, w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, f,
          w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, w, w, f, w, w,
          w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, f, w, w, w, f, w, f, w, w, w, f, w, w, w, w,
          w, f, w, f, w],
         [w, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f, f, f, f, f,
          w, f, w, f, f, f, f, f, f, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, f, f, w, f, f, f,
          f, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, f, f, w, f, w, f, w, f, f, f, f, f, w, f, f, f,
          f, f, w, f, w],
         [w, f, w, w, w, w, w, f, w, f, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, f, w, f, w, w, w, w,
          w, f, w, f, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, w,
          w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, w, w, f, w, f, w, w, w, w, w, f, w, w, w, f,
          w, w, w, f, w],
         [w, f, f, f, w, f, f, f, f, f, f, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f, w, f, f, f, w, f,
          f, f, w, f, f, f, w, f, f, f, f, f, f, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f,
          f, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f,
          w, f, f, f, w],
         [w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, w, w, w, w, f, w, w,
          w, w, w, f, w, w, w, w, w, w, w, w, w, f, w, f, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, w,
          w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, f, w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, w,
          w, f, w, w, w],
         [w, f, w, f, w, f, w, f, f, f, f, f, f, f, f, f, f, f, f, f, w, f, w, f, w, f, f, f, w, f, f, f,
          f, f, f, f, w, f, f, f, f, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f, f, f, f, f, f, f, w, f,
          f, f, w, f, w, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f,
          w, f, f, f, w],
         [w, f, w, f, w, f, w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, f, w, w,
          w, w, w, w, w, f, w, w, w, w, w, f, w, w, w, w, w, f, w, f, w, w, w, f, w, w, w, w, w, f, w, f,
          w, w, w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, f, w, f, w, w, w, w, w, f, w, f, w, w, w, f,
          w, w, w, f, w],
         [w, f, w, f, w, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f, f, f, w, f, w, f, f, f,
          w, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, w, f, w, f, f, f, w, f,
          w, f, f, f, w, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, w, f, f, f,
          w, f, f, f, w],
         [w, w, w, f, w, f, w, f, w, w, w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, w,
          w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, f, w, f, w, f, w, w, w, f,
          w, f, w, w, w, f, w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, f, w, w, w, w, w, f, w, w,
          w, f, w, w, w],
         [w, f, f, f, w, f, w, f, f, f, w, f, w, f, w, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f,
          w, f, w, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, w, f, f, f,
          w, f, f, f, f, f, w, f, f, f, f, f, f, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, w, f, w, f,
          f, f, f, f, w],
         [w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, f, w, f, w, w, w, w, w, f, w, w, w, w, w, w, w, f,
          w, f, w, f, w, f, w, f, w, f, w, f, w, f, w, w, w, f, w, w, w, w, w, w, w, f, w, w, w, f, w, w,
          w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, f, w, f, w, w, w, f, w, w, w, f, w, w,
          w, w, w, f, w],
         [w, f, f, f, f, f, f, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f, f, f, f, f, f, f,
          f, f, w, f, f, f, w, f, f, f, w, f, f, f, f, f, w, f, f, f, f, f, f, f, f, f, f, f, w, f, f, f,
          f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, f, w, f, f, f, w, f, f, f, f, f, f, f,
          f, f, f, f, w],
         [w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w,
          w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, f, w, w, w, w, w, w, w, w, w, w, w, w,
          w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w, w,
          w, w, w, w, w]])
